### ISSUE TITLE
Missing 'noexcept' on current_path(error_code&)

### ISSUE THREAD

**Issue by jwakely** [cplusplus/filesystem-ts#10]
The second overload in [fs.op.current_path] takes an `error_code` so should be `noexcept`

**Comment by Dani-Hub** [comment]
I disagree. noexcept should only be added, if the "committee agrees that the function cannot throw", but this might happen during the dynamic allocation on function return. See the rationale provided for

http://cplusplus.github.io/filesystem-ts/defects.html#37

**Comment by villevoutilainen** [comment]
Well, if an error occurs, current_path's overload taking an error_code is specified to return path(), which cannot throw.

**Comment by Dani-Hub** [comment]
But this point might be too late, when the return value is produced. Your argumentation works only, if RVO would be required.

**Comment by villevoutilainen** [comment]
When the return value is produced, errors in producing it can be caught. When the return value is returned, I expect it will use path's move constructor, which is again noexcept.

**Comment by Dani-Hub** [comment]
I don't think that this was part of the original design or functions marked with error_code, especially given the fact that [fs.err.report] p11 doesn't refer to allocation failures, contrary to [fs.err.report] p8. I think we need to extend [fs.err.report] p11 as well to include allocation failure to realize what you seem to intend.

**Comment by jwakely** [comment]
Thanks, Daniel
