### ISSUE TITLE
[fs.op.system_complete] refers to undefined variable 'base'

### ISSUE THREAD

**Issue by jwakely** [cplusplus/filesystem-ts#11]
> or `p` and `base` have the same `root_name()`

`base` is not defined, I believe it refers to the value returned by `current_path()`

**Comment by Beman** [comment]
Issue opened on the official issues list. See http://cplusplus.github.io/filesystem-ts/active.html#70

Once an issue is opened on the official issues list, it is closed on the GitHub issue tracker.
