### ISSUE TITLE
Errors in [fs.op.copy]

### ISSUE THREAD

**Issue by jwakely** [cplusplus/filesystem-ts#12]
15.3 [fs.op.copy] paragraph 16 says:

> then `copy_symlink(from, to, options)`.

But there is no overload of `copy_symlink` that takes a `copy_options`, it should be `copy_symlink(from, to)`.

Paragraph 26 says

> as if by `for (directory_entry& x : directory_iterator(from))`

but the result of dereferencing a `directory_iterator` is const, it should be:

> as if by `for (const directory_entry& x : directory_iterator(from))`

**Comment by Beman** [comment]
Issue opened on the official issues list. See http://cplusplus.github.io/filesystem-ts/active.html#71

Once an issue is opened on the official issues list, it is closed on the GitHub issue tracker.
