### ISSUE TITLE
Should is_empty use error_code in its specification?

### ISSUE THREAD

**Issue by jwakely** [cplusplus/filesystem-ts#13]
The descriptions of most functions are explicit about the use of the `ec` argument, either saying something like  "`foo(p)` or `foo(p, ec)`, respectively" or using the `ec` argument like <code>foo(p<i>[, ec]</i>)</code>, but `is_empty` does not.

 [fs.op.is_empty]/2 refers to `ec` unconditionally, but more importantly [fs.op.is_empty]/3 doesn't pass `ec` to the `directory_iterator` constructor or the `file_size` function.

**Comment by Beman** [comment]
Issue opened on the official issues list. See http://cplusplus.github.io/filesystem-ts/active.html#72

Once an issue is opened on the official issues list, it is closed on the GitHub issue tracker.
