### ISSUE TITLE
[fs.op.status] effects cannot be implemented as specified

### ISSUE THREAD

**Issue by jwakely** [cplusplus/filesystem-ts#17]
[[fs.op.status](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4099.html#fs.op.status)] paragraph 2 says:

> _Effects:_ As if:
> 
>    error_code ec;
>    file_status result = status(p, ec);
>    if (result == file_type::none)

This won't compile, there is no comparison operator for `file_status` and `file_type`, and the conversion from `file_type` to `file_status` is explicit.

Proposed resolution:

> _Effects:_ As if:
>    error_code ec;
>    file_status result = status(p, ec);
>    if (result<INS>.type()</INS> == file_type::none)

**Comment by Beman** [comment]
Please check http://cplusplus.github.io/filesystem-ts/active.html#73

Thanks,

--Beman
