### ISSUE TITLE
Errors in [rec.dir.itr.members] p40

### ISSUE THREAD

**Issue by jwakely** [cplusplus/filesystem-ts#9]
> Otherwise if `recursion_pending() && is_directory(this->status())  
>   && (!is_symlink(this->symlink_status())`

`recursive_directory_iterator` does not have `status` or `symlink_status` members, it should say something like

> Otherwise if `recursion_pending() && is_directory((*this)->status())  
>   && (!is_symlink((*this)->symlink_status())`

**Comment by Beman** [comment]
Issue opened on the official issues list. See http://cplusplus.github.io/filesystem-ts/active.html#69

Once an issue is opened on the official issues list, it is closed on the GitHub issue tracker.
